### ISSUE TITLE
Request for shopping utilities

### ISSUE THREAD

**Issue by dglonsdale** [googleads/googleads-perl-lib#10]
Please provide shopping utilities described in Google Ads Developer blog of 24 March

**Comment by dglonsdale** [comment]
I do not require the utilities at the current time, but would like an idea of the elapsed time that would be required to build them for when I am ready to make a firm request.

**Comment by jradcliff** [comment]
Thanks for registering your interest. At this point, we're gathering votes to determine the level of interest for each library.

Based on the effort involved for this for the Java library, porting over to the Perl library won't be a trivial task, but **if more users comment on this issue** we'll look to prioritize the work.

**Comment by sundquist** [comment]
This has been up on the board for awhile without any additional votes. Unfortunately, this means that we don't have enough support to back up adding this to the library. As a result, I'm going to close this out as something that we will not be adding. If someone comes along and decides that this is of high priority, please reach out here.

Best,
Nadine Sundquist, AdWords API Team
