### ISSUE TITLE
Versioning for for non-Adwords API code?

### ISSUE THREAD

**Issue by mcmillhj** [googleads/googleads-perl-lib#16]
Lately we have been performing API upgrades much more frequently given the increased release cycle for the Adwords API. We have trouble migrating sometimes because code in the Common/ or AdWords/ subdirectories differs between versions and we have no insight into those changes. These leads to some of our services not functioning as we expect when we upgrade. 

Is it possible to version these directories along with the Adwords API code? Then we could point at the version we would like to use.

**Comment by sundquist** [comment]
Hello,

The Common directory does have its own version in Google::Ads::Common::Constants. As for the AdWords directory, when there is a version change x.y.z, a change in y usually indicates that the AdWords directory has changed. So much of the code (such as the examples) relies on what's in the AdWords directory that the AdWords directory having its own version independent of the overall version may cause a bit of confusion. One of the things that may help is taking a look at the commit history in GitHub. For example, the last version had these changes (https://github.com/googleads/googleads-perl-lib/commit/ca7187f38a8761c3b4b5d6dda3ef355799665bd8). 

Best,
Nadine Sundquist, AdWords API Team
