### ISSUE TITLE
Reporting errors no longer call `warn()` as of version 4.4.0

### ISSUE THREAD

**Issue by mcmillhj** [googleads/googleads-perl-lib#17]
We save reports from the API to a file using the `Google::Ads::Common::ReportUtils` object, below is a simplified version of how we save reports:

    my $handler = Google::Ads::Common::ReportUtils::get_report_handler(
          $call_args->{report_definition}, 
          $self->gapi_client->get_google_client 
    );
    my $response = $handler->save( $call_args->{filename} );

in version 4.3.0, any issues that occurred while returning the report would be logged and then the Perl `warn()` function was called. This all happened via the [`logwarn()`](https://github.com/googleads/googleads-perl-lib/blob/v4.3.0/lib/Google/Ads/Common/ReportDownloadHandler.pm#L257) subroutine of the Logger object returned by `Google::Ads::AdWords::Logging::get_soap_logger`. This was nice because we could then write a handler like this to turn the `warn()` into a `die()`:

    local $SIG{__WARN__} = sub { die "@_"; };

in version [4.4.0](https://github.com/googleads/googleads-perl-lib/blob/v4.4.0/lib/Google/Ads/Common/ReportDownloadHandler.pm#L268), the `logwarn()` subroutine was replaced with a call to the `error()` subroutine 

Not having a way to hook into this makes it difficult for us to handle errors elegantly, the Logger object appears to have other methods such as [`error_die()`](https://metacpan.org/pod/Log::Log4perl#Log-and-die-or-warn) or [`error_warn()`](https://metacpan.org/pod/Log::Log4perl#Log-and-die-or-warn) which could be used instead of `error()` and would allow us to hook into this via a Signal handler.

**Comment by pickardj79** [comment]
Did u mean to add more to the issue

**Comment by sundquist** [comment]
Hello,

Thanks for providing this feedback on your use case. This change was made during a general cleanup of the library to make it a bit more consistent. I'll take a look to see what I can do about making it easier for you to use a handler.

Best,
Nadine Sundquist, AdWords API Team

**Comment by sundquist** [comment]
Greetings!

In version [4.11.0](https://github.com/googleads/googleads-perl-lib/releases/tag/v4.11.0) of the client library, I introduced l**ogwarn()** back into the place where it was removed. That will let you hook back into it with a signal handler.

Cheers,
Nadine Sundquist, AdWords API Team
