### ISSUE TITLE
 Error in setting up client library 

### ISSUE THREAD

**Issue by bhavyahdas** [googleads/googleads-perl-lib#19]
I was trying to setup API access. I followed steps mentioned in https://developers.google.com/adwords/api/docs/guides/first-api-call website. Chose perl as my language. While setting up client library,I am getting below error ( I followed steps https://github.com/googleads/googleads-perl-lib/wiki/API-access-using-own-credentials-(installed-application-flow) )

Execution command:

$ perl generate_offline_credentials.pl

Error:
Use of uninitialized value in concatenation (.) or string at ../../lib/Google/Ads/Common/HTTPTransport.pm line 32.
ERROR: Missing input values for oAuth2ClientId or oAuth2ClientSecret in your adwords.properties file. These values can be generated from the Google Developers Console https://console.developers.google.com under the Projects tab. at generate_offline_credentials.pl line 39.

I had placed adwords.properties file under home directory, and edited  oAuth2ClientId, oAuth2ClientSecret variables in it.

Could you please help me in finding what went wrong?

**Comment by sundquist** [comment]
Greetings!

Thanks for providing all the steps that you went through. Based on your prompt, it looks like your system is Linux based.

It sounds like you already did an **ls ~** to make sure that your adwords.properties file is there. Can you also verify that you don't have a **#** sign commenting out the **OAuth2ClientId** and the **oAuth2ClientSecret**? Also, please verify that you don't have any spaces on either side of the equals sign. It should look similar to the following with the **insert** values filled in.

> oAuth2ClientId=**insertClientIdHere**
> oAuth2ClientSecret=**insertClientSecretHere**
> 

If you find that you're still experiencing difficulties, please get back to me.

Best,
Nadine Sundquist, AdWords API Team
