### ISSUE TITLE
Implement die_on_faults in _refresh_token call

### ISSUE THREAD

**Issue by matjmat** [googleads/googleads-perl-lib#20]
Hi, would it be possible to implement the $client->get_die_on_faults() check on the _refresh_token call.

In : Google/Ads/Common/OAuth2ApplicationsHandler.pm

Replace : 
 if (!$res->is_success()) {
    warn($res->decoded_content());
    return 0;
  }

By:
 if (!$res->is_success()) {
    my $res_warning = $res->decoded_content();
    if ( $self->get_die_on_faults() ) {
     die($res_warning);
    } else {
     warn($res_warning);
    }
    return 0;
  }

However the get_die_on_faults() is not available in this package so I don't have a runnable fix to provide.

That would simplify catching an invalid_grant error from the refresh_token call.

Thanks.

Mathieu

**Comment by sundquist** [comment]
Hello Mathieu,

Thanks for the suggestion! I'll take a look to see what can be done. I just want to make sure to stay backwards compatible for people who are already using the call a certain way, but it looks like what you've provided is a good start in giving that a try. I'll take a look soon. Hopefully, I'll come up with something that works for everyone.

Cheers,
Nadine Sundquist, AdWords API Team

**Comment by sundquist** [comment]
Hi Mathieu,

I got this fixed in 5.0.0. Thanks for pointing it out.

Best,
Nadine Sundquist, AdWords API Team

**Comment by matjmat** [comment]
Thanks Nadine !
