### ISSUE TITLE
Stop declaring dependency on HTTP::Server::Simple::CGI

### ISSUE THREAD

**Issue by JRaspass** [googleads/googleads-perl-lib#27]
None of the code actually depends on this module, it is only referenced in the example code in https://github.com/googleads/googleads-perl-lib/blob/master/examples/oauth/authenticate_with_web_flow.pl

Drop the declaration from https://github.com/googleads/googleads-perl-lib/blob/master/Build.PL

**Comment by sundquist** [comment]
Hello,

I'll see what I can do about that. It is one that isn't used very often, so I can see your point on this.

Best,
Nadine Sundquist, AdWords API Team

**Comment by BenRKarl** [comment]
Closing this as this repo will be archived and all Perl users should (if not already) migrate to the new [library](https://github.com/googleads/google-ads-perl) for the [Google Ads API](https://developers.google.com/google-ads/api/docs/client-libs/perl).
