### ISSUE TITLE
Migration to Google Ads API

### ISSUE THREAD

**Issue by matjmat** [googleads/googleads-perl-lib#30]
Hi,
 following the deprecation schedules page of the API, I saw that the v21809 version will be deprecated in 2020 so we'll need to migrate all of our code to the Google Ads API : https://developers.google.com/google-ads/api/docs/start

 Perl is not listed in the available libraries, so my question is it going to be provided or not ?

 Thanks !

Mathieu

**Comment by matjmat** [comment]
It seems a new version is available here : https://metacpan.org/release/WFANSH/Google-Ads-GoogleAds-Client-2.0.0

@google-admin  is it the expected lib to use now that the current one is set for deprecation ?

**Comment by BenRKarl** [comment]
@matjmat yes indeed, you can find the source code for the new library [here](https://github.com/googleads/google-ads-perl) and documentation is [here](https://developers.google.com/google-ads/api/docs/client-libs/perl).
