### ISSUE TITLE
Feature request for enabling logging in Google::Ads::Common::ReportUtils

### ISSUE THREAD

**Issue by pickardj79** [googleads/googleads-perl-lib#5]
Google::Ads::AdWords has logging enabled in Serializer.pm and Deserializer.pm through either (a) Google::Ads::AdWords::Logging::enable_soap_logging or (b) last_soap_request / last_soap_response in the Google::Ads::AdWords::Client object. The reporting service, Google::Ads::Common::ReportUtils, provides no such facility that I can see. We'd like Google to add logging to this module through either one of the ways it is enabled through the Serializer/Deserializer. Ideally, we'd like to see the soap that is being sent and the soap that is being received (or at least the headers from the response). Thanks!

**Comment by jradcliff** [comment]
Fixed in [v3.2.1](https://github.com/googleads/googleads-perl-lib/releases/tag/v3.2.1).
